In [1]:
#import numpy
import numpy as np

In [5]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5]) #from list

# Perform basic arithmetic operations
print('Adding 2 to each elements: ',arr + 2)
print('Multiplation by 2 to each elements: ',arr * 2) 

Adding 2 to each elements:  [3 4 5 6 7]
Multiplation by 2 to each elements:  [ 2  4  6  8 10]


In [9]:

# Calculate the sum and mean of the array
print('The sum is: ',np.sum(arr))
print('The mean value is: ',np.mean(arr))

The sum is:  15
The mean value is:  3.0


In [17]:
# Generate a random NumPy array
rand_arr = np.random.rand(3)
print('\nRandom Array of 3 element is: \n',rand_arr)


Random Array of 3 element is: 
 [0.94622834 0.97109503 0.00715096]


In [13]:

rand_arr = np.random.rand(3, 3)
print('\nRandom Array of 3x3 is: \n',rand_arr)


Random Array of 3x3 is: 
 [[0.03090999 0.19005039 0.71816789]
 [0.9341699  0.63746186 0.74374669]
 [0.07241305 0.84431546 0.83086939]]


In [4]:
arr = np.array((1, 2, 3, 4, 5)) #from tuple

# Perform basic arithmetic operations
print('Adding 2 to each elements: ',arr + 2)
print('Multiplation by 2 to each elements: ',arr * 2) 

# Calculate the sum and mean of the array
print('The sum is: ',np.sum(arr))
print('The mean value is: ',np.mean(arr))

# Generate a random NumPy array
rand_arr = np.random.rand(3)
print('\nRandom Array of 3 element is: \n',rand_arr)

rand_arr = np.random.rand(3, 3)
print('\nRandom Array of 3x3 is: \n',rand_arr)

Adding 2 to each elements:  [3 4 5 6 7]
Multiplation by 2 to each elements:  [ 2  4  6  8 10]
The sum is:  15
The mean value is:  3.0

Random Array of 3 element is: 
 [0.585559   0.47819591 0.50068787]

Random Array of 3x3 is: 
 [[0.61742108 0.56688788 0.73718218]
 [0.60573031 0.58388365 0.82089827]
 [0.88436557 0.71937723 0.0735546 ]]


Examples of Broadcasting

In [19]:
# Example 1: Adding a scalar to an array
arr = np.array([1, 2, 3])
scalar = 2
result = arr + scalar

print('Adding a scalar to an array: \n', result)

Adding a scalar to an array: 
 [3 4 5]


In [29]:
# Example 2: Adding two arrays with different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array([4])
result = arr1 + arr2

print('Adding two arrays with different shapes: \n',result)

Adding two arrays with different shapes: 
 [5 6 7]


In [23]:
# Example 3: Multiplying two arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([5, 6])
result = arr1 * arr2
print('Multiplying two arrays with different shapes\n')
print(result)

Multiplying two arrays with different shapes

[[ 5 12]
 [15 24]]


Example of Indexing

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

1
5


Example of Slicing

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:5])
print(arr[1:8:2]) 

[2 3 4 5]
[2 4 6 8]


Multi-Dimensional Indexing and Slicing
For multi-dimensional arrays, you can use comma-separated indices to access specific elements or subsets. For example

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1]) 
print(arr[1:, 1:])

2
[5 8]


Advanced Indexing
NumPy also supports advanced indexing using arrays of indices.

In [35]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(arr[indices])

[1 3 5]


In [39]:
# import numpy as np

# Generate an array of 5 random numbers between 0 and 1
arr = np.random.rand(5)
print(arr)

# Generate an array of 3 random numbers from a normal distribution
arr = np.random.randn(3)
print(arr)

# Generate an array of 4 random integers between 1 and 10
arr = np.random.randint(1, 11, 4)
print(arr)

# Generate an array of 2 random samples from a given array
arr = np.array([1, 2, 3, 4, 5])
samples = np.random.choice(arr, 2)
print(samples)

[0.88541871 0.91553271 0.19140355 0.40467716 0.14738125]
[ 1.21036778 -0.71581986  0.36638378]
[ 9 10  2  5]
[5 1]


In [41]:
# int: Integer data type
# In NumPy, you can create an integer array using the dtype parameter. 
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # int32

# You can also specify the bit width of the integer using np.int8, np.int16, np.int32, or np.int64.

int32


In [13]:
# float: Floating-point data type
# In NumPy, you can create a floating-point array using the dtype parameter.

arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float32)
print(arr.dtype)

# You can also specify the precision of the floating-point number using np.float32 or np.float64.

float32


In [19]:
# complex: Complex number data type
# In NumPy, you can create a complex number array using the dtype parameter.

arr = np.array([1 + 2j, 2 + 3j, 3 + 4j], dtype=np.complex128)
print(arr.dtype) 

# You can also specify the precision of the complex number using np.complex64 or np.complex128.

complex128


In [17]:
# bool: Boolean data type
# In NumPy, you can create a boolean array using the dtype parameter.
arr = np.array([True, False, True, False], dtype=np.bool_)
print(arr.dtype)
print(arr)

bool
[ True False  True False]


In [27]:
# string: String data type (Note: This is not a built-in NumPy data type)
# NumPy does not have a built-in string data type. However, you can use the dtype parameter to specify a string type using the numpy.object_ type.

arr = np.array(['hello', 'world', 'numpy'], dtype=np.object_)
print(arr.dtype) 

# Alternatively, you can use the numpy.string_ type, which is a fixed-length string type.

# arr = np.array(['hello', 'world', 'numpy'], dtype=np.string_(10))
# print(arr.dtype)

# Note that the numpy.string_ type is deprecated since NumPy 1.14, and it's recommended to use the numpy.object_ type instead.

object


NumPy is primarily designed for numerical computations, and it's not ideal for working with strings. However, there are some scenarios where you might need to work with strings in NumPy, and that's why NumPy provides some limited support for strings.

Here are some reasons why strings are used in NumPy:

Labeling and annotation: In scientific computing, it's common to have arrays with labels or annotations that are strings. For example, you might have an array of temperatures with labels like "Celsius" or "Fahrenheit".
Categorical data: In data analysis, you might have categorical data that's represented as strings. For example, you might have an array of colors like "red", "green", or "blue".
Data import and export: When importing or exporting data from files, strings are often used to represent column names, headers, or other metadata.
Interoperability with other libraries: NumPy is often used in conjunction with other Python libraries like Pandas, Matplotlib, or Scikit-learn, which may require working with strings.
When working with strings in NumPy, you should be aware of the following limitations:

Performance: String operations in NumPy can be slower than numerical operations.
Memory usage: Strings can occupy more memory than numerical data types.
Limited functionality: NumPy's string support is limited compared to dedicated string libraries like Python's built-in str type or libraries like Pandas.
If you need to work with strings extensively, it's often better to use a dedicated library like Pandas, which provides more efficient and flexible string handling capabilities.

In summary, while NumPy is primarily designed for numerical computations, it provides some limited support for strings to accommodate specific use cases and interoperability with other libraries. However, if you need to work with strings extensively, you may want to consider using a more specialized library.

In [23]:
# Creating a NumPy array with strings
arr = np.array(['hello', 'world', 'nu'])
print(arr.dtype)

arr = np.array(['hello', 'world', 'numpy'], dtype='U10')
print(arr.dtype)

<U5
<U10


NumPy arrays have several attributes that provide information about the array. Here are some of the most commonly used attributes:

ndim: The number of dimensions in the array.
shape: A tuple representing the dimensionality of the array.
size: The total number of elements in the array.
dtype: The data type of the elements in the array.
itemsize: The length of each element in bytes.
nbytes: The total number of bytes used by the array.
flags: Information about the memory layout of the array.
strides: The number of bytes to step in each dimension when traversing the array.
data: A pointer to the start of the array's data.
ctypes: An object that can be used to access the array's data as a ctypes object.
flat: A 1-D iterator over the array.
real, imag, conj: Attributes for complex arrays.
T: The transpose of the array.


In [31]:
# ndim: The number of dimensions in the array.
arr = np.array([1, 2, 3])
print(arr.ndim)

1


In [57]:
# shape: A tuple representing the dimensionality of the array.
arr = np.array([[1], [2], [3], [4]])
print(arr.shape)
print(arr[1][0])

(4, 1)
2


In [53]:
# size: The total number of elements in the array.
arr = np.array([1, 2, 3])
# arr = np.array([[1], [2], [3], [4]])
print(arr.size)

3


In [50]:
# dtype: The data type of the elements in the array.
arr = np.array([1, 2, 3])
print(arr.dtype)

int32


In [43]:
# itemsize: The length of each element in bytes.
arr = np.array([1, 2, 3])
print(arr.itemsize)
print(arr.dtype)

4
int32
